ALTER TABLE "Word"
  ADD COLUMN IF NOT EXISTS "repetitionCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "intervalDays" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "easeFactor" DOUBLE PRECISION NOT NULL DEFAULT 2.5,
  ADD COLUMN IF NOT EXISTS "nextReviewAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "lastReviewedAt" TIMESTAMP(3);
